### ISSUE TITLE
Help: Latin-English wiktionary dictionary not working on Koreader

### ISSUE THREAD

**Issue by hzhangab** [Vuizur/Wiktionary-Dictionaries#1]
Hi Vuizur,

I tried loading the latin-english wiktionary dictionary files into koreader and it does not work. Not only this dictionary cannot be found in Koreader, none of the other dictionaries under the directory (that originally works) can be detected by Koreader either after the files of this dictionary was put in the directory.

Do you have any thoughts on this issue? Any help/thoughts would be appreciated.

**Comment by Vuizur** [comment]
Hello,

I tried to reproduce the error, but the dictionary seemed to work for me. But I noticed that downloading it from Github is not very intuitive and revamped the code for the dictionary creation system. Could you try to download it again? The file is now a tar.gz file that can be opened in 7-zip, for example. Inside there is a folder that should be put into the koreader dictionary folder.

**Comment by hzhangab** [comment]
Thank you! I will try that and let you know.

Thank you very much for your help!

**Comment by hzhangab** [comment]
I used the tar.gz file and it worked, thank you.

Now the issue is that entries with macrons in the .syn file cannot be found if the keyword is entered without macrons. For example, "exhausit" can be found, but not "gustāverimus." Any help is appreciated.

**Comment by Vuizur** [comment]
I added additional inflections of the words without macrons and breves to the dictionary. So in theory it should work now without the new version.

**Comment by hzhangab** [comment]
Working great!

Thank you. The dictionary is really helpful.
